// API-Football이 K3/K4 대부분 구단의 스쿼드를 아예 안 주기 때문에(팀 정보/일정만 있고 선수단 없음),
// 나무위키 각 구단 문서에 정리되어 있는 선수단 명단을 수동으로 옮겨온다(사용자 요청, 2026-08-08).
// 사진/국적/나이 등 상세 정보는 나무위키에 없는 경우가 많아 number/position/name만 채우고 나머지는 null 처리.
// 팀 ID는 apiFootballAdapter.js의 K3K4_TEAM_NAME_OVERRIDES와 동일한 API-Football team id를 사용한다.
import { lookupK3K4PlayerPhoto } from "./k3k4PlayerPhotos.js";

// k3k4PlayerPhotos.js의 키("팀명|이름")와 매칭하기 위한 team id -> 팀명(사진 등록 시 쓴 표기 그대로).
const TEAM_NAME_FOR_PHOTO_LOOKUP = {
  7056: "부산교통공사축구단",
  7083: "경주한수원FC",
};

export const MANUAL_K3K4_SQUADS = {
  7105: [ // 시흥시민축구단
    { number: 1, position: "GK", name: "주현성" },
    { number: 21, position: "GK", name: "김동건" },
    { number: 31, position: "GK", name: "강성혁" },
    { number: 2, position: "DF", name: "이남규" },
    { number: 3, position: "DF", name: "박현준" },
    { number: 5, position: "DF", name: "신일수" },
    { number: 6, position: "DF", name: "안지호" },
    { number: 7, position: "DF", name: "박형진" },
    { number: 13, position: "DF", name: "김남성" },
    { number: 15, position: "DF", name: "여재욱" },
    { number: 16, position: "DF", name: "한승원" },
    { number: 20, position: "DF", name: "오창권" },
    { number: 24, position: "DF", name: "김민성" },
    { number: 26, position: "DF", name: "남현욱" },
    { number: 33, position: "DF", name: "권우빈" },
    { number: 40, position: "DF", name: "조한수" },
    { number: 44, position: "DF", name: "허신현" },
    { number: 98, position: "DF", name: "나준영" },
    { number: 4, position: "MF", name: "김효찬" },
    { number: 8, position: "MF", name: "황신중" },
    { number: 12, position: "MF", name: "박한결" },
    { number: 19, position: "MF", name: "안은산" },
    { number: 23, position: "MF", name: "이석현" },
    { number: 25, position: "MF", name: "김태현" },
    { number: 27, position: "MF", name: "곽승조" },
    { number: 29, position: "MF", name: "전진" },
    { number: 32, position: "MF", name: "서유민" },
    { number: 42, position: "MF", name: "양준영" },
    { number: 66, position: "MF", name: "천세윤" },
    { number: 72, position: "MF", name: "배재윤" },
    { number: 88, position: "MF", name: "구민준" },
    { number: 9, position: "FW", name: "공민현" },
    { number: 10, position: "FW", name: "김다원" },
    { number: 11, position: "FW", name: "김경구" },
    { number: 14, position: "FW", name: "김태헌" },
    { number: 18, position: "FW", name: "다나카 하루토" },
    { number: 30, position: "FW", name: "정철웅" },
    { number: 34, position: "FW", name: "박성결" },
    { number: 37, position: "FW", name: "권완규" },
    { number: 47, position: "FW", name: "이정재" },
    { number: 70, position: "FW", name: "이하람" },
    { number: 77, position: "FW", name: "김홍" },
  ],
  7099: [ // 포천시민축구단
    { number: 1, position: "GK", name: "김준성" },
    { number: 25, position: "GK", name: "김종혁" },
    { number: 31, position: "GK", name: "신건우" },
    { number: 2, position: "DF", name: "김태은" },
    { number: 5, position: "DF", name: "서찬욱" },
    { number: 12, position: "DF", name: "이서준" },
    { number: 13, position: "DF", name: "유용현" },
    { number: 20, position: "DF", name: "심현민" },
    { number: 22, position: "DF", name: "임준우" },
    { number: 23, position: "DF", name: "최승호" },
    { number: 26, position: "DF", name: "서도현" },
    { number: 29, position: "DF", name: "김수안" },
    { number: 33, position: "DF", name: "이영규" },
    { number: 6, position: "MF", name: "전산해" },
    { number: 8, position: "MF", name: "정현식" },
    { number: 14, position: "MF", name: "김현중" },
    { number: 15, position: "MF", name: "정병주" },
    { number: 16, position: "MF", name: "한규진" },
    { number: 17, position: "MF", name: "황제" },
    { number: 24, position: "MF", name: "이철희" },
    { number: 30, position: "MF", name: "류상우" },
    { number: 7, position: "FW", name: "김정현" },
    { number: 9, position: "FW", name: "이석규" },
    { number: 10, position: "FW", name: "이재건" },
    { number: 11, position: "FW", name: "이태민" },
    { number: 18, position: "FW", name: "유선우" },
    { number: 19, position: "FW", name: "홍석환" },
    { number: 21, position: "FW", name: "박주경" },
    { number: 27, position: "FW", name: "박준범" },
    { number: 28, position: "FW", name: "김현민" },
    { number: 32, position: "FW", name: "김승섭" },
    { number: 36, position: "FW", name: "온예카 오비존" },
  ],
  7056: [ // 부산교통공사축구단
    { number: 1, position: "GK", name: "최진백" },
    { number: 21, position: "GK", name: "최원우" },
    { number: 31, position: "GK", name: "이민수" },
    { number: 2, position: "DF", name: "박재우" },
    { number: 3, position: "DF", name: "오현교" },
    { number: 4, position: "DF", name: "김민수" },
    { number: 13, position: "DF", name: "지의수" },
    { number: 15, position: "DF", name: "조우현" },
    { number: 19, position: "DF", name: "윤철현" },
    { number: 27, position: "DF", name: "김준섭" },
    { number: 42, position: "DF", name: "김민성" },
    { number: 6, position: "MF", name: "하용주" },
    { number: 8, position: "MF", name: "안치우" },
    { number: 22, position: "MF", name: "조용준" },
    { number: 23, position: "MF", name: "최우담" },
    { number: 29, position: "MF", name: "양우진" },
    { number: 66, position: "MF", name: "배수민" },
    { number: 7, position: "FW", name: "이윤재" },
    { number: 9, position: "FW", name: "얀" },
    { number: 10, position: "FW", name: "김양우" },
    { number: 11, position: "FW", name: "박희수" },
    { number: 14, position: "FW", name: "김도훈" },
    { number: 17, position: "FW", name: "김승준" },
    { number: 18, position: "FW", name: "윤경원" },
    { number: 77, position: "FW", name: "공다휘" },
    { number: 90, position: "FW", name: "양정운" },
  ],
  18653: [ // 당진시민축구단
    { number: 1, position: "GK", name: "최영은" },
    { number: 13, position: "GK", name: "임준석" },
    { number: 21, position: "GK", name: "김세형" },
    { number: 3, position: "DF", name: "이한빈" },
    { number: 6, position: "DF", name: "신재욱" },
    { number: 14, position: "DF", name: "여준영" },
    { number: 20, position: "DF", name: "김주형" },
    { number: 23, position: "DF", name: "홍준서" },
    { number: 25, position: "DF", name: "임동주" },
    { number: 42, position: "DF", name: "이현조" },
    { number: 66, position: "DF", name: "이선호" },
    { number: 71, position: "DF", name: "신일연" },
    { number: 4, position: "MF", name: "최시온" },
    { number: 7, position: "MF", name: "류연준" },
    { number: 8, position: "MF", name: "이은재" },
    { number: 16, position: "MF", name: "김세웅" },
    { number: 18, position: "MF", name: "이현우" },
    { number: 26, position: "MF", name: "임성현" },
    { number: 27, position: "MF", name: "현상진" },
    { number: 28, position: "MF", name: "이승규" },
    { number: 30, position: "MF", name: "신동민" },
    { number: 33, position: "MF", name: "정영웅" },
    { number: 35, position: "MF", name: "민승기" },
    { number: 77, position: "MF", name: "이시명" },
    { number: 88, position: "MF", name: "백세현" },
    { number: 9, position: "FW", name: "강현종" },
    { number: 10, position: "FW", name: "서도협" },
    { number: 11, position: "FW", name: "최세윤" },
    { number: 15, position: "FW", name: "지상욱" },
    { number: 17, position: "FW", name: "한준영" },
    { number: 19, position: "FW", name: "김현중" },
    { number: 22, position: "FW", name: "한창구" },
    { number: 47, position: "FW", name: "김수성" },
    { number: 72, position: "FW", name: "김동률" },
    { number: 99, position: "FW", name: "김형진" },
  ],
  7083: [ // 경주한수원FC
    { number: 12, position: "GK", name: "이성주" },
    { number: 25, position: "GK", name: "김정호" },
    { number: 31, position: "GK", name: "이성주" },
    { number: 81, position: "GK", name: "최철원" },
    { number: 2, position: "DF", name: "이종현" },
    { number: 3, position: "DF", name: "장효강" },
    { number: 4, position: "DF", name: "이우연" },
    { number: 14, position: "DF", name: "류승범" },
    { number: 16, position: "DF", name: "장지성" },
    { number: 18, position: "DF", name: "문승원" },
    { number: 20, position: "DF", name: "정호근" },
    { number: 23, position: "DF", name: "최지호" },
    { number: 26, position: "DF", name: "서승우" },
    { number: 62, position: "DF", name: "장유섭" },
    { number: 5, position: "MF", name: "하재진" },
    { number: 6, position: "MF", name: "임대준" },
    { number: 7, position: "MF", name: "정상규" },
    { number: 8, position: "MF", name: "안수민" },
    { number: 10, position: "MF", name: "주한성" },
    { number: 13, position: "MF", name: "박성원" },
    { number: 33, position: "MF", name: "현상엽" },
    { number: 45, position: "MF", name: "이예찬" },
    { number: 77, position: "MF", name: "국관우" },
    { number: 9, position: "FW", name: "이형경" },
    { number: 11, position: "FW", name: "빅토르" },
    { number: 17, position: "FW", name: "황대영" },
    { number: 19, position: "FW", name: "정성호" },
    { number: 22, position: "FW", name: "전정호" },
    { number: 27, position: "FW", name: "유신" },
    { number: 29, position: "FW", name: "최기석" },
    { number: 80, position: "FW", name: "진성욱" },
  ],
  7111: [ // 양평FC
    { number: 1, position: "GK", name: "심민" },
    { number: 31, position: "GK", name: "박다니엘" },
    { number: 41, position: "GK", name: "신재민" },
    { number: 2, position: "DF", name: "김병수" },
    { number: 3, position: "DF", name: "윤상은" },
    { number: 4, position: "DF", name: "김드미트리" },
    { number: 16, position: "DF", name: "양민석" },
    { number: 17, position: "DF", name: "김형겸" },
    { number: 20, position: "DF", name: "차인석" },
    { number: 42, position: "DF", name: "장재혁" },
    { number: 44, position: "DF", name: "정수환" },
    { number: 5, position: "MF", name: "이용수" },
    { number: 6, position: "MF", name: "이태형" },
    { number: 7, position: "MF", name: "윤병우" },
    { number: 8, position: "MF", name: "유청인" },
    { number: 10, position: "MF", name: "김동욱" },
    { number: 12, position: "MF", name: "이상오" },
    { number: 13, position: "MF", name: "윤양균" },
    { number: 14, position: "MF", name: "김대협" },
    { number: 15, position: "MF", name: "이정근" },
    { number: 18, position: "MF", name: "장동혁" },
    { number: 21, position: "MF", name: "이도영" },
    { number: 22, position: "MF", name: "이찬솔" },
    { number: 27, position: "MF", name: "조현준" },
    { number: 30, position: "MF", name: "이민혁" },
    { number: 34, position: "MF", name: "김예성" },
    { number: 47, position: "MF", name: "권구민" },
    { number: 48, position: "MF", name: "남궁환" },
    { number: 55, position: "MF", name: "성민준" },
    { number: 62, position: "MF", name: "황건" },
    { number: 72, position: "MF", name: "안성재" },
    { number: 74, position: "MF", name: "김재영" },
    { number: 75, position: "MF", name: "강성화" },
    { number: 77, position: "MF", name: "조영진" },
    { number: 88, position: "MF", name: "최민혁" },
    { number: 9, position: "FW", name: "덴젤" },
    { number: 23, position: "FW", name: "곽래승" },
    { number: 26, position: "FW", name: "이규서" },
    { number: 33, position: "FW", name: "클린즈만" },
    { number: 90, position: "FW", name: "브레노" },
  ],
  16452: [ // 진주시민축구단
    { number: 1, position: "GK", name: "김원중" },
    { number: 23, position: "GK", name: "배준호" },
    { number: 30, position: "GK", name: "김희수" },
    { number: 2, position: "DF", name: "김지운" },
    { number: 3, position: "DF", name: "박시율" },
    { number: 4, position: "DF", name: "서태경" },
    { number: 6, position: "DF", name: "김호영" },
    { number: 7, position: "DF", name: "김진래" },
    { number: 10, position: "DF", name: "장효준" },
    { number: 15, position: "DF", name: "윤도원" },
    { number: 16, position: "DF", name: "하금성" },
    { number: 22, position: "DF", name: "차준수" },
    { number: 27, position: "DF", name: "임경백" },
    { number: 66, position: "DF", name: "한동훈" },
    { number: 70, position: "DF", name: "이승환" },
    { number: 88, position: "DF", name: "이호영" },
    { number: 8, position: "MF", name: "임민혁" },
    { number: 13, position: "MF", name: "김성현" },
    { number: 14, position: "MF", name: "유창훈" },
    { number: 17, position: "MF", name: "구본준" },
    { number: 19, position: "MF", name: "한상욱" },
    { number: 24, position: "MF", name: "최민서" },
    { number: 26, position: "MF", name: "최익진" },
    { number: 72, position: "MF", name: "천지현" },
    { number: 9, position: "FW", name: "이동규" },
    { number: 11, position: "FW", name: "전용준" },
    { number: 18, position: "FW", name: "김소웅" },
    { number: 28, position: "FW", name: "아이작 오세이" },
    { number: 81, position: "FW", name: "김도윤" },
    { number: 99, position: "FW", name: "김민영" },
  ],
  27863: [ // 진천HRFC (나무위키 문서에 포지션 구분 없이 등번호만 있어 임의로 채우지 않고 전부 null 처리)
    { number: 1, position: null, name: "임채권" },
    { number: 2, position: null, name: "여은수" },
    { number: 3, position: null, name: "김우석" },
    { number: 5, position: null, name: "장현호" },
    { number: 6, position: null, name: "송홍민" },
    { number: 70, position: null, name: "홍현승" },
    { number: 72, position: null, name: "박성준" },
    { number: 7, position: null, name: "홍기욱" },
    { number: 8, position: null, name: "유종우" },
    { number: 11, position: null, name: "김상경" },
    { number: 14, position: null, name: "신원호" },
    { number: 15, position: null, name: "김강연" },
    { number: 16, position: null, name: "이준석" },
    { number: 17, position: null, name: "박경주" },
    { number: 18, position: null, name: "이민석" },
    { number: 22, position: null, name: "김강국" },
    { number: 23, position: null, name: "김현우" },
    { number: 24, position: null, name: "정동우" },
    { number: 27, position: null, name: "조민호" },
    { number: 45, position: null, name: "김상진" },
    { number: 47, position: null, name: "최산" },
    { number: 77, position: null, name: "김강호" },
    { number: 88, position: null, name: "이태희" },
    { number: 9, position: null, name: "김태양" },
    { number: 10, position: null, name: "홍수호" },
    { number: 12, position: null, name: "이현규" },
    { number: 13, position: null, name: "김승우" },
    { number: 19, position: null, name: "박민서" },
    { number: 31, position: null, name: "김성훈" },
    { number: 33, position: null, name: "이환희" },
    { number: 43, position: null, name: "오준서" },
    { number: 71, position: null, name: "김건" },
    { number: 90, position: null, name: "임유민" },
    { number: 97, position: null, name: "김민서" },
    { number: 99, position: null, name: "황치윤" },
  ],
  18654: [ // 거제시민축구단
    { number: 1, position: "GK", name: "신지훈" },
    { number: 21, position: "GK", name: "이준" },
    { number: 31, position: "GK", name: "김승준" },
    { number: 2, position: "DF", name: "황태현" },
    { number: 3, position: "DF", name: "이주원" },
    { number: 4, position: "DF", name: "손혜창" },
    { number: 5, position: "DF", name: "김환" },
    { number: 6, position: "DF", name: "문영준" },
    { number: 13, position: "DF", name: "두현석" },
    { number: 14, position: "DF", name: "김주헌" },
    { number: 15, position: "DF", name: "윤광운" },
    { number: 16, position: "DF", name: "윤여준" },
    { number: 30, position: "DF", name: "박건" },
    { number: 36, position: "DF", name: "김재환" },
    { number: 7, position: "MF", name: "김경환" },
    { number: 8, position: "MF", name: "김준형" },
    { number: 10, position: "MF", name: "박한빈" },
    { number: 19, position: "MF", name: "김태형" },
    { number: 23, position: "MF", name: "최재훈" },
    { number: 27, position: "MF", name: "정상" },
    { number: 28, position: "MF", name: "김현민" },
    { number: 88, position: "MF", name: "박정훈" },
    { number: 9, position: "FW", name: "이시창" },
    { number: 11, position: "FW", name: "노의왕" },
    { number: 17, position: "FW", name: "김민창" },
    { number: 18, position: "FW", name: "김영준" },
    { number: 20, position: "FW", name: "최주혁" },
    { number: 25, position: "FW", name: "최동관" },
    { number: 90, position: "FW", name: "최다흰" },
    { number: 91, position: "FW", name: "박건웅" },
    { number: 99, position: "FW", name: "김건우" },
  ],
  27865: [ // 서산 파이오니아 FC (구 서산에프씨, 조직명은 아직 서산FC 유지 - joinKFA 표기 혼선 주의)
    { number: 1, position: "GK", name: "조지웅" },
    { number: 13, position: "GK", name: "박원철" },
    { number: 31, position: "GK", name: "김진화" },
    { number: 40, position: "GK", name: "이상현" },
    { number: 51, position: "GK", name: "조주영" },
    { number: 2, position: "DF", name: "정무영" },
    { number: 3, position: "DF", name: "원기연" },
    { number: 4, position: "DF", name: "구본준" },
    { number: 5, position: "DF", name: "하현수" },
    { number: 12, position: "DF", name: "권승현" },
    { number: 15, position: "DF", name: "장규성" },
    { number: 16, position: "DF", name: "민선홍" },
    { number: 17, position: "DF", name: "김기환" },
    { number: 18, position: "DF", name: "이재용" },
    { number: 20, position: "DF", name: "이유재" },
    { number: 23, position: "DF", name: "박지우" },
    { number: 24, position: "DF", name: "손홍범" },
    { number: 26, position: "DF", name: "양효종" },
    { number: 29, position: "DF", name: "최성광" },
    { number: 32, position: "DF", name: "김정우" },
    { number: 35, position: "DF", name: "김규빈" },
    { number: 6, position: "MF", name: "김이근" },
    { number: 8, position: "MF", name: "백상훈" },
    { number: 14, position: "MF", name: "이지원" },
    { number: 21, position: "MF", name: "이승준" },
    { number: 22, position: "MF", name: "이진석" },
    { number: 27, position: "MF", name: "김민우" },
    { number: 28, position: "MF", name: "홍진현" },
    { number: 34, position: "MF", name: "배원준" },
    { number: 38, position: "MF", name: "김민준" },
    { number: 41, position: "MF", name: "이준혁" },
    { number: 42, position: "MF", name: "김대원" },
    { number: 44, position: "MF", name: "이승재" },
    { number: 47, position: "MF", name: "홍재훈" },
    { number: 7, position: "FW", name: "변재영" },
    { number: 9, position: "FW", name: "김훈옥" },
    { number: 10, position: "FW", name: "윤동권" },
    { number: 11, position: "FW", name: "박지열" },
    { number: 19, position: "FW", name: "엄하은" },
    { number: 25, position: "FW", name: "안기훈" },
    { number: 30, position: "FW", name: "김해수" },
    { number: 37, position: "FW", name: "김도형" },
    { number: 39, position: "FW", name: "김기현" },
    { number: 45, position: "FW", name: "홍준혁" },
  ],
};

// 프론트(teamDetail.js)의 포지션 그룹핑이 API-Football 원문 표기(Goalkeeper/Defender/Midfielder/
// Attacker)를 기준으로 하기 때문에, 나무위키에서 옮겨온 GK/DF/MF/FW 약어를 그에 맞춰 변환한다.
const POSITION_FULL_NAME = { GK: "Goalkeeper", DF: "Defender", MF: "Midfielder", FW: "Attacker" };

// API-Football이 K3/K4는 스쿼드를 아예 안 주거나(0명), 극히 일부만 등록해둔 경우(예: 3명)가 있어서
// "1명이라도 있으면 그대로 쓴다"로는 부족하다 - 실제 팀은 최소 20명 이상이라 이 미만이면 미완성으로
// 보고 나무위키 전체 명단으로 대체한다(진주시민축구단 등에서 확인, 2026-08-08).
const API_SQUAD_MIN_SIZE = 15;

export function lookupManualK3K4Squad(teamId, existingSquadLength) {
  if (existingSquadLength >= API_SQUAD_MIN_SIZE) return null; // API-Football이 충분한 스쿼드를 주면 그걸 우선한다
  const roster = MANUAL_K3K4_SQUADS[Number(teamId)];
  if (!roster) return null;
  const teamName = TEAM_NAME_FOR_PHOTO_LOOKUP[Number(teamId)];
  return roster.map((p) => ({
    id: `manual-${teamId}-${p.number}`,
    name: p.name,
    position: POSITION_FULL_NAME[p.position] || null,
    nationality: null,
    number: p.number,
    age: null,
    photo: teamName ? lookupK3K4PlayerPhoto(teamName, p.name) : null,
  }));
}
