// API-Football이 K3/K4 대부분 구단의 스쿼드를 아예 안 주기 때문에(팀 정보/일정만 있고 선수단 없음),
// 나무위키 각 구단 문서에 정리되어 있는 선수단 명단을 수동으로 옮겨온다(사용자 요청, 2026-08-08).
// 사진/국적/나이 등 상세 정보는 나무위키에 없는 경우가 많아 number/position/name만 채우고 나머지는 null 처리.
// 팀 ID는 apiFootballAdapter.js의 K3K4_TEAM_NAME_OVERRIDES와 동일한 API-Football team id를 사용한다.
import { lookupK3K4PlayerPhoto } from "./k3k4PlayerPhotos.js";

// k3k4PlayerPhotos.js의 키("팀명|이름")와 매칭하기 위한 team id -> 팀명(사진 등록 시 쓴 표기 그대로).
const TEAM_NAME_FOR_PHOTO_LOOKUP = {
  7056: "부산교통공사축구단",
  7083: "경주한수원FC",
};

export const MANUAL_K3K4_SQUADS = {
  7105: [ // 시흥시민축구단
    { number: 1, position: "GK", name: "주현성" },
    { number: 21, position: "GK", name: "김동건" },
    { number: 31, position: "GK", name: "강성혁" },
    { number: 2, position: "DF", name: "이남규" },
    { number: 3, position: "DF", name: "박현준" },
    { number: 5, position: "DF", name: "신일수" },
    { number: 6, position: "DF", name: "안지호" },
    { number: 7, position: "DF", name: "박형진" },
    { number: 13, position: "DF", name: "김남성" },
    { number: 15, position: "DF", name: "여재욱" },
    { number: 16, position: "DF", name: "한승원" },
    { number: 20, position: "DF", name: "오창권" },
    { number: 24, position: "DF", name: "김민성" },
    { number: 26, position: "DF", name: "남현욱" },
    { number: 33, position: "DF", name: "권우빈" },
    { number: 40, position: "DF", name: "조한수" },
    { number: 44, position: "DF", name: "허신현" },
    { number: 98, position: "DF", name: "나준영" },
    { number: 4, position: "MF", name: "김효찬" },
    { number: 8, position: "MF", name: "황신중" },
    { number: 12, position: "MF", name: "박한결" },
    { number: 19, position: "MF", name: "안은산" },
    { number: 23, position: "MF", name: "이석현" },
    { number: 25, position: "MF", name: "김태현" },
    { number: 27, position: "MF", name: "곽승조" },
    { number: 29, position: "MF", name: "전진" },
    { number: 32, position: "MF", name: "서유민" },
    { number: 42, position: "MF", name: "양준영" },
    { number: 66, position: "MF", name: "천세윤" },
    { number: 72, position: "MF", name: "배재윤" },
    { number: 88, position: "MF", name: "구민준" },
    { number: 9, position: "FW", name: "공민현" },
    { number: 10, position: "FW", name: "김다원" },
    { number: 11, position: "FW", name: "김경구" },
    { number: 14, position: "FW", name: "김태헌" },
    { number: 18, position: "FW", name: "다나카 하루토" },
    { number: 30, position: "FW", name: "정철웅" },
    { number: 34, position: "FW", name: "박성결" },
    { number: 37, position: "FW", name: "권완규" },
    { number: 47, position: "FW", name: "이정재" },
    { number: 70, position: "FW", name: "이하람" },
    { number: 77, position: "FW", name: "김홍" },
  ],
  7099: [ // 포천시민축구단
    { number: 1, position: "GK", name: "김준성" },
    { number: 25, position: "GK", name: "김종혁" },
    { number: 31, position: "GK", name: "신건우" },
    { number: 2, position: "DF", name: "김태은" },
    { number: 5, position: "DF", name: "서찬욱" },
    { number: 12, position: "DF", name: "이서준" },
    { number: 13, position: "DF", name: "유용현" },
    { number: 20, position: "DF", name: "심현민" },
    { number: 22, position: "DF", name: "임준우" },
    { number: 23, position: "DF", name: "최승호" },
    { number: 26, position: "DF", name: "서도현" },
    { number: 29, position: "DF", name: "김수안" },
    { number: 33, position: "DF", name: "이영규" },
    { number: 6, position: "MF", name: "전산해" },
    { number: 8, position: "MF", name: "정현식" },
    { number: 14, position: "MF", name: "김현중" },
    { number: 15, position: "MF", name: "정병주" },
    { number: 16, position: "MF", name: "한규진" },
    { number: 17, position: "MF", name: "황제" },
    { number: 24, position: "MF", name: "이철희" },
    { number: 30, position: "MF", name: "류상우" },
    { number: 7, position: "FW", name: "김정현" },
    { number: 9, position: "FW", name: "이석규" },
    { number: 10, position: "FW", name: "이재건" },
    { number: 11, position: "FW", name: "이태민" },
    { number: 18, position: "FW", name: "유선우" },
    { number: 19, position: "FW", name: "홍석환" },
    { number: 21, position: "FW", name: "박주경" },
    { number: 27, position: "FW", name: "박준범" },
    { number: 28, position: "FW", name: "김현민" },
    { number: 32, position: "FW", name: "김승섭" },
    { number: 36, position: "FW", name: "온예카 오비존" },
  ],
  7056: [ // 부산교통공사축구단
    { number: 1, position: "GK", name: "최진백" },
    { number: 21, position: "GK", name: "최원우" },
    { number: 31, position: "GK", name: "이민수" },
    { number: 2, position: "DF", name: "박재우" },
    { number: 3, position: "DF", name: "오현교" },
    { number: 4, position: "DF", name: "김민수" },
    { number: 13, position: "DF", name: "지의수" },
    { number: 15, position: "DF", name: "조우현" },
    { number: 19, position: "DF", name: "윤철현" },
    { number: 27, position: "DF", name: "김준섭" },
    { number: 42, position: "DF", name: "김민성" },
    { number: 6, position: "MF", name: "하용주" },
    { number: 8, position: "MF", name: "안치우" },
    { number: 22, position: "MF", name: "조용준" },
    { number: 23, position: "MF", name: "최우담" },
    { number: 29, position: "MF", name: "양우진" },
    { number: 66, position: "MF", name: "배수민" },
    { number: 7, position: "FW", name: "이윤재" },
    { number: 9, position: "FW", name: "얀" },
    { number: 10, position: "FW", name: "김양우" },
    { number: 11, position: "FW", name: "박희수" },
    { number: 14, position: "FW", name: "김도훈" },
    { number: 17, position: "FW", name: "김승준" },
    { number: 18, position: "FW", name: "윤경원" },
    { number: 77, position: "FW", name: "공다휘" },
    { number: 90, position: "FW", name: "양정운" },
  ],
  18653: [ // 당진시민축구단
    { number: 1, position: "GK", name: "최영은" },
    { number: 13, position: "GK", name: "임준석" },
    { number: 21, position: "GK", name: "김세형" },
    { number: 3, position: "DF", name: "이한빈" },
    { number: 6, position: "DF", name: "신재욱" },
    { number: 14, position: "DF", name: "여준영" },
    { number: 20, position: "DF", name: "김주형" },
    { number: 23, position: "DF", name: "홍준서" },
    { number: 25, position: "DF", name: "임동주" },
    { number: 42, position: "DF", name: "이현조" },
    { number: 66, position: "DF", name: "이선호" },
    { number: 71, position: "DF", name: "신일연" },
    { number: 4, position: "MF", name: "최시온" },
    { number: 7, position: "MF", name: "류연준" },
    { number: 8, position: "MF", name: "이은재" },
    { number: 16, position: "MF", name: "김세웅" },
    { number: 18, position: "MF", name: "이현우" },
    { number: 26, position: "MF", name: "임성현" },
    { number: 27, position: "MF", name: "현상진" },
    { number: 28, position: "MF", name: "이승규" },
    { number: 30, position: "MF", name: "신동민" },
    { number: 33, position: "MF", name: "정영웅" },
    { number: 35, position: "MF", name: "민승기" },
    { number: 77, position: "MF", name: "이시명" },
    { number: 88, position: "MF", name: "백세현" },
    { number: 9, position: "FW", name: "강현종" },
    { number: 10, position: "FW", name: "서도협" },
    { number: 11, position: "FW", name: "최세윤" },
    { number: 15, position: "FW", name: "지상욱" },
    { number: 17, position: "FW", name: "한준영" },
    { number: 19, position: "FW", name: "김현중" },
    { number: 22, position: "FW", name: "한창구" },
    { number: 47, position: "FW", name: "김수성" },
    { number: 72, position: "FW", name: "김동률" },
    { number: 99, position: "FW", name: "김형진" },
  ],
  7083: [ // 경주한수원FC
    { number: 12, position: "GK", name: "이성주" },
    { number: 25, position: "GK", name: "김정호" },
    { number: 31, position: "GK", name: "이성주" },
    { number: 81, position: "GK", name: "최철원" },
    { number: 2, position: "DF", name: "이종현" },
    { number: 3, position: "DF", name: "장효강" },
    { number: 4, position: "DF", name: "이우연" },
    { number: 14, position: "DF", name: "류승범" },
    { number: 16, position: "DF", name: "장지성" },
    { number: 18, position: "DF", name: "문승원" },
    { number: 20, position: "DF", name: "정호근" },
    { number: 23, position: "DF", name: "최지호" },
    { number: 26, position: "DF", name: "서승우" },
    { number: 62, position: "DF", name: "장유섭" },
    { number: 5, position: "MF", name: "하재진" },
    { number: 6, position: "MF", name: "임대준" },
    { number: 7, position: "MF", name: "정상규" },
    { number: 8, position: "MF", name: "안수민" },
    { number: 10, position: "MF", name: "주한성" },
    { number: 13, position: "MF", name: "박성원" },
    { number: 33, position: "MF", name: "현상엽" },
    { number: 45, position: "MF", name: "이예찬" },
    { number: 77, position: "MF", name: "국관우" },
    { number: 9, position: "FW", name: "이형경" },
    { number: 11, position: "FW", name: "빅토르" },
    { number: 17, position: "FW", name: "황대영" },
    { number: 19, position: "FW", name: "정성호" },
    { number: 22, position: "FW", name: "전정호" },
    { number: 27, position: "FW", name: "유신" },
    { number: 29, position: "FW", name: "최기석" },
    { number: 80, position: "FW", name: "진성욱" },
  ],
  7111: [ // 양평FC
    { number: 1, position: "GK", name: "심민" },
    { number: 31, position: "GK", name: "박다니엘" },
    { number: 41, position: "GK", name: "신재민" },
    { number: 2, position: "DF", name: "김병수" },
    { number: 3, position: "DF", name: "윤상은" },
    { number: 4, position: "DF", name: "김드미트리" },
    { number: 16, position: "DF", name: "양민석" },
    { number: 17, position: "DF", name: "김형겸" },
    { number: 20, position: "DF", name: "차인석" },
    { number: 42, position: "DF", name: "장재혁" },
    { number: 44, position: "DF", name: "정수환" },
    { number: 5, position: "MF", name: "이용수" },
    { number: 6, position: "MF", name: "이태형" },
    { number: 7, position: "MF", name: "윤병우" },
    { number: 8, position: "MF", name: "유청인" },
    { number: 10, position: "MF", name: "김동욱" },
    { number: 12, position: "MF", name: "이상오" },
    { number: 13, position: "MF", name: "윤양균" },
    { number: 14, position: "MF", name: "김대협" },
    { number: 15, position: "MF", name: "이정근" },
    { number: 18, position: "MF", name: "장동혁" },
    { number: 21, position: "MF", name: "이도영" },
    { number: 22, position: "MF", name: "이찬솔" },
    { number: 27, position: "MF", name: "조현준" },
    { number: 30, position: "MF", name: "이민혁" },
    { number: 34, position: "MF", name: "김예성" },
    { number: 47, position: "MF", name: "권구민" },
    { number: 48, position: "MF", name: "남궁환" },
    { number: 55, position: "MF", name: "성민준" },
    { number: 62, position: "MF", name: "황건" },
    { number: 72, position: "MF", name: "안성재" },
    { number: 74, position: "MF", name: "김재영" },
    { number: 75, position: "MF", name: "강성화" },
    { number: 77, position: "MF", name: "조영진" },
    { number: 88, position: "MF", name: "최민혁" },
    { number: 9, position: "FW", name: "덴젤" },
    { number: 23, position: "FW", name: "곽래승" },
    { number: 26, position: "FW", name: "이규서" },
    { number: 33, position: "FW", name: "클린즈만" },
    { number: 90, position: "FW", name: "브레노" },
  ],
  16452: [ // 진주시민축구단 (공식 사이트 jinjufc.co.kr 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "김원중", photo: "/img/k3k4players/jinju/jinju_김원중.jpg" },
    { number: 23, position: "GK", name: "배준호", photo: "/img/k3k4players/jinju/jinju_배준호.jpg" },
    { number: 30, position: "GK", name: "김희수", photo: "/img/k3k4players/jinju/jinju_김희수.jpg" },
    { number: 2, position: "DF", name: "김지운", photo: "/img/k3k4players/jinju/jinju_김지운.jpg" },
    { number: 3, position: "DF", name: "박시율", photo: "/img/k3k4players/jinju/jinju_박시율.jpg" },
    { number: 4, position: "DF", name: "서태경", photo: "/img/k3k4players/jinju/jinju_서태경.jpg" },
    { number: 6, position: "DF", name: "김호영", photo: "/img/k3k4players/jinju/jinju_김호영.jpg" },
    { number: 7, position: "DF", name: "김진래", photo: "/img/k3k4players/jinju/jinju_김진래.jpg" },
    { number: 10, position: "DF", name: "장효준", photo: "/img/k3k4players/jinju/jinju_장효준.jpg" },
    { number: 15, position: "DF", name: "윤도원", photo: "/img/k3k4players/jinju/jinju_윤도원.jpg" },
    { number: 16, position: "DF", name: "하금성", photo: "/img/k3k4players/jinju/jinju_하금성.jpg" },
    { number: 22, position: "DF", name: "박세현", photo: "/img/k3k4players/jinju/jinju_박세현.jpg" },
    { number: 27, position: "DF", name: "임경백", photo: "/img/k3k4players/jinju/jinju_임경백.jpg" },
    { number: 66, position: "DF", name: "한동훈", photo: "/img/k3k4players/jinju/jinju_한동훈.jpg" },
    { number: 70, position: "DF", name: "이승환", photo: "/img/k3k4players/jinju/jinju_이승환.jpg" },
    { number: 88, position: "DF", name: "이호영", photo: "/img/k3k4players/jinju/jinju_이호영.jpg" },
    { number: 8, position: "MF", name: "임민혁", photo: "/img/k3k4players/jinju/jinju_임민혁.jpg" },
    { number: 13, position: "MF", name: "김성현", photo: "/img/k3k4players/jinju/jinju_김성현.jpg" },
    { number: 14, position: "MF", name: "유창훈", photo: "/img/k3k4players/jinju/jinju_유창훈.jpg" },
    { number: 17, position: "MF", name: "구본준", photo: "/img/k3k4players/jinju/jinju_구본준.jpg" },
    { number: 24, position: "MF", name: "최민서", photo: "/img/k3k4players/jinju/jinju_최민서.jpg" },
    { number: 26, position: "MF", name: "최익진", photo: "/img/k3k4players/jinju/jinju_최익진.jpg" },
    { number: 71, position: "MF", name: "정우빈", photo: "/img/k3k4players/jinju/jinju_정우빈.jpg" },
    { number: 72, position: "MF", name: "천지현", photo: "/img/k3k4players/jinju/jinju_천지현.jpg" },
    { number: 9, position: "FW", name: "이동규", photo: "/img/k3k4players/jinju/jinju_이동규.jpg" },
    { number: 11, position: "FW", name: "전용준", photo: "/img/k3k4players/jinju/jinju_전용준.jpg" },
    { number: 18, position: "FW", name: "김소웅", photo: "/img/k3k4players/jinju/jinju_김소웅.jpg" },
    { number: 19, position: "FW", name: "한상욱", photo: "/img/k3k4players/jinju/jinju_한상욱.jpg" },
    { number: 28, position: "FW", name: "아이작 오세이", photo: "/img/k3k4players/jinju/jinju_Osei.jpg" },
    { number: 81, position: "FW", name: "김도윤", photo: "/img/k3k4players/jinju/jinju_김도윤.jpg" },
    { number: 99, position: "FW", name: "김민영", photo: "/img/k3k4players/jinju/jinju_김민영.jpg" },
  ],
  27863: [ // 진천HRFC (공식 사이트 highroutefc.com 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "임채권", photo: "/img/k3k4players/jincheon/jincheon_임채권.jpg" },
    { number: 13, position: "GK", name: "김승우", photo: "/img/k3k4players/jincheon/jincheon_김승우.jpg" },
    { number: 31, position: "GK", name: "김성훈", photo: "/img/k3k4players/jincheon/jincheon_김성훈.jpg" },
    { number: 99, position: "GK", name: "황치윤", photo: "/img/k3k4players/jincheon/jincheon_황치윤.jpg" },
    { number: 2, position: "DF", name: "여은수", photo: "/img/k3k4players/jincheon/jincheon_여은수.jpg" },
    { number: 3, position: "DF", name: "김우석", photo: "/img/k3k4players/jincheon/jincheon_김우석.jpg" },
    { number: 4, position: "DF", name: "공호원", photo: "/img/k3k4players/jincheon/jincheon_공호원.jpg" },
    { number: 5, position: "DF", name: "장현호", photo: "/img/k3k4players/jincheon/jincheon_장현호.jpg" },
    { number: 8, position: "DF", name: "유종우", photo: "/img/k3k4players/jincheon/jincheon_유종우.jpg" },
    { number: 12, position: "DF", name: "이현규", photo: "/img/k3k4players/jincheon/jincheon_이현규.jpg" },
    { number: 14, position: "DF", name: "신원호", photo: "/img/k3k4players/jincheon/jincheon_신원호.jpg" },
    { number: 15, position: "DF", name: "김강연", photo: "/img/k3k4players/jincheon/jincheon_김강연.jpg" },
    { number: 16, position: "DF", name: "이준석", photo: "/img/k3k4players/jincheon/jincheon_이준석.jpg" },
    { number: 23, position: "DF", name: "김현우", photo: "/img/k3k4players/jincheon/jincheon_김현우.jpg" },
    { number: 24, position: "DF", name: "정동우", photo: "/img/k3k4players/jincheon/jincheon_정동우.jpg" },
    { number: 25, position: "DF", name: "박종현", photo: "/img/k3k4players/jincheon/jincheon_박종현.jpg" },
    { number: 43, position: "DF", name: "오준서", photo: "/img/k3k4players/jincheon/jincheon_오준서.jpg" },
    { number: 45, position: "DF", name: "김상진", photo: "/img/k3k4players/jincheon/jincheon_김상진.jpg" },
    { number: 6, position: "MF", name: "송홍민", photo: "/img/k3k4players/jincheon/jincheon_송홍민.jpg" },
    { number: 7, position: "MF", name: "홍기욱", photo: "/img/k3k4players/jincheon/jincheon_홍기욱.jpg" },
    { number: 10, position: "MF", name: "홍수호", photo: "/img/k3k4players/jincheon/jincheon_홍수호.jpg" },
    { number: 17, position: "MF", name: "박경주", photo: "/img/k3k4players/jincheon/jincheon_박경주.jpg" },
    { number: 21, position: "MF", name: "김종현", photo: "/img/k3k4players/jincheon/jincheon_김종현.jpg" },
    { number: 27, position: "MF", name: "조민호", photo: "/img/k3k4players/jincheon/jincheon_조민호.jpg" },
    { number: 28, position: "MF", name: "최윤빈", photo: "/img/k3k4players/jincheon/jincheon_최윤빈.jpg" },
    { number: 33, position: "MF", name: "이환희", photo: "/img/k3k4players/jincheon/jincheon_이환희.jpg" },
    { number: 42, position: "MF", name: "백성우", photo: "/img/k3k4players/jincheon/jincheon_백성우.jpg" },
    { number: 47, position: "MF", name: "최산", photo: "/img/k3k4players/jincheon/jincheon_최산.jpg" },
    { number: 70, position: "MF", name: "홍현승", photo: "/img/k3k4players/jincheon/jincheon_홍현승.jpg" },
    { number: 88, position: "MF", name: "이태희", photo: "/img/k3k4players/jincheon/jincheon_이태희.jpg" },
    { number: 9, position: "FW", name: "김태양", photo: "/img/k3k4players/jincheon/jincheon_김태양.jpg" },
    { number: 11, position: "FW", name: "김상경", photo: "/img/k3k4players/jincheon/jincheon_김상경.jpg" },
    { number: 18, position: "FW", name: "이민석", photo: "/img/k3k4players/jincheon/jincheon_이민석.jpg" },
    { number: 19, position: "FW", name: "박민서", photo: "/img/k3k4players/jincheon/jincheon_박민서.jpg" },
    { number: 71, position: "FW", name: "김건", photo: "/img/k3k4players/jincheon/jincheon_김건.jpg" },
    { number: 72, position: "FW", name: "박성준", photo: "/img/k3k4players/jincheon/jincheon_박성준.jpg" },
    { number: 77, position: "FW", name: "김강호", photo: "/img/k3k4players/jincheon/jincheon_김강호.jpg" },
    { number: 90, position: "FW", name: "임유민", photo: "/img/k3k4players/jincheon/jincheon_임유민.jpg" },
    { number: 97, position: "FW", name: "김민서", photo: "/img/k3k4players/jincheon/jincheon_김민서.jpg" },
  ],
  7092: [ // 서울중랑축구단
    { number: 1, position: "GK", name: "백영빈" },
    { number: 2, position: "GK", name: "배승호" },
    { number: 3, position: "DF", name: "권석주" },
    { number: 4, position: "DF", name: "전이찬" },
    { number: 5, position: "DF", name: "선예준" },
    { number: 6, position: "DF", name: "이풍범" },
    { number: 7, position: "MF", name: "이동현" },
    { number: 8, position: "MF", name: "정대현" },
    { number: 9, position: "MF", name: "이채운" },
    { number: 10, position: "MF", name: "한서진" },
    { number: 11, position: "MF", name: "이종욱" },
    { number: 12, position: "MF", name: "최민서" },
    { number: 13, position: "MF", name: "노승준" },
    { number: 14, position: "MF", name: "김재성" },
    { number: 15, position: "MF", name: "임유석" },
    { number: 16, position: "MF", name: "고준영" },
    { number: 17, position: "MF", name: "전병진" },
    { number: 18, position: "FW", name: "홍윤성" },
    { number: 19, position: "FW", name: "진현준" },
    { number: 20, position: "FW", name: "방우진" },
    { number: 21, position: "FW", name: "문민성" },
    { number: 22, position: "FW", name: "김민준" },
    { number: 23, position: "FW", name: "나동욱" },
    { number: 24, position: "FW", name: "이상민" },
    { number: 25, position: "FW", name: "박지석" },
    { number: 26, position: "FW", name: "이제욱" },
    { number: 27, position: "FW", name: "유찬희" },
    { number: 30, position: "FW", name: "김민욱" },
    { number: 32, position: "FW", name: "정진호" },
    { number: 33, position: "FW", name: "김지훈" },
    { number: 37, position: "FW", name: "이은재" },
    { number: 47, position: "FW", name: "장은찬" },
    { number: 70, position: "FW", name: "안준혁" },
    { number: 88, position: "FW", name: "조민규" },
    { number: 91, position: "FW", name: "송재호" },
  ],
  18654: [ // 거제시민축구단 (공식 사이트 거제도민프로축구단.kr 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "신지훈", photo: "/img/k3k4players/geoje/geoje_신지훈.jpg" },
    { number: 21, position: "GK", name: "이준", photo: "/img/k3k4players/geoje/geoje_이준.jpg" },
    { number: 31, position: "GK", name: "김승준", photo: "/img/k3k4players/geoje/geoje_김승준.jpg" },
    { number: 2, position: "DF", name: "황태현", photo: "/img/k3k4players/geoje/geoje_황태현.jpg" },
    { number: 3, position: "DF", name: "이주원", photo: "/img/k3k4players/geoje/geoje_이주원.jpg" },
    { number: 4, position: "DF", name: "손혜창", photo: "/img/k3k4players/geoje/geoje_손혜창.jpg" },
    { number: 5, position: "DF", name: "김환", photo: "/img/k3k4players/geoje/geoje_김환.jpg" },
    { number: 6, position: "DF", name: "문영준", photo: "/img/k3k4players/geoje/geoje_문영준.jpg" },
    { number: 13, position: "DF", name: "두현석", photo: "/img/k3k4players/geoje/geoje_두현석.jpg" },
    { number: 14, position: "DF", name: "김주헌", photo: "/img/k3k4players/geoje/geoje_김주헌.jpg" },
    { number: 15, position: "DF", name: "윤광운", photo: "/img/k3k4players/geoje/geoje_윤광운.jpg" },
    { number: 16, position: "DF", name: "윤여준", photo: "/img/k3k4players/geoje/geoje_윤여준.jpg" },
    { number: 36, position: "DF", name: "김재환", photo: "/img/k3k4players/geoje/geoje_김재환.jpg" },
    { number: 7, position: "MF", name: "김경환", photo: "/img/k3k4players/geoje/geoje_김경환.jpg" },
    { number: 8, position: "MF", name: "김준형", photo: "/img/k3k4players/geoje/geoje_김준형.jpg" },
    { number: 10, position: "MF", name: "박한빈", photo: "/img/k3k4players/geoje/geoje_박한빈.jpg" },
    { number: 19, position: "MF", name: "김태형", photo: "/img/k3k4players/geoje/geoje_김태형.jpg" },
    { number: 23, position: "MF", name: "최재훈", photo: "/img/k3k4players/geoje/geoje_최재훈.jpg" },
    { number: 27, position: "MF", name: "정상", photo: "/img/k3k4players/geoje/geoje_정상.jpg" },
    { number: 28, position: "MF", name: "김현민", photo: "/img/k3k4players/geoje/geoje_김현민.jpg" },
    { number: 88, position: "MF", name: "박정훈", photo: "/img/k3k4players/geoje/geoje_박정훈.jpg" },
    { number: 9, position: "FW", name: "이시창", photo: "/img/k3k4players/geoje/geoje_이시창.jpg" },
    { number: 11, position: "FW", name: "노의왕", photo: "/img/k3k4players/geoje/geoje_노의왕.jpg" },
    { number: 17, position: "FW", name: "김민창", photo: "/img/k3k4players/geoje/geoje_김민창.jpg" },
    { number: 18, position: "FW", name: "김영준", photo: "/img/k3k4players/geoje/geoje_김영준.jpg" },
    { number: 20, position: "FW", name: "최주혁", photo: "/img/k3k4players/geoje/geoje_최주혁.jpg" },
    { number: 25, position: "FW", name: "최동관", photo: "/img/k3k4players/geoje/geoje_최동관.jpg" },
    { number: 29, position: "FW", name: "주영재", photo: "/img/k3k4players/geoje/geoje_주영재.jpg" },
    { number: 70, position: "FW", name: "손영윤", photo: "/img/k3k4players/geoje/geoje_손영윤.jpg" },
    { number: 90, position: "FW", name: "최다흰", photo: "/img/k3k4players/geoje/geoje_최다흰.jpg" },
    { number: 91, position: "FW", name: "박건웅", photo: "/img/k3k4players/geoje/geoje_박건웅.jpg" },
    { number: 99, position: "FW", name: "김건우", photo: "/img/k3k4players/geoje/geoje_김건우.jpg" },
  ],
  27865: [ // 서산 파이오니아 FC (구 서산에프씨, 조직명은 아직 서산FC 유지 - joinKFA 표기 혼선 주의)
    { number: 1, position: "GK", name: "조지웅" },
    { number: 13, position: "GK", name: "박원철" },
    { number: 31, position: "GK", name: "김진화" },
    { number: 40, position: "GK", name: "이상현" },
    { number: 51, position: "GK", name: "조주영" },
    { number: 2, position: "DF", name: "정무영" },
    { number: 3, position: "DF", name: "원기연" },
    { number: 4, position: "DF", name: "구본준" },
    { number: 5, position: "DF", name: "하현수" },
    { number: 12, position: "DF", name: "권승현" },
    { number: 15, position: "DF", name: "장규성" },
    { number: 16, position: "DF", name: "민선홍" },
    { number: 17, position: "DF", name: "김기환" },
    { number: 18, position: "DF", name: "이재용" },
    { number: 20, position: "DF", name: "이유재" },
    { number: 23, position: "DF", name: "박지우" },
    { number: 24, position: "DF", name: "손홍범" },
    { number: 26, position: "DF", name: "양효종" },
    { number: 29, position: "DF", name: "최성광" },
    { number: 32, position: "DF", name: "김정우" },
    { number: 35, position: "DF", name: "김규빈" },
    { number: 6, position: "MF", name: "김이근" },
    { number: 8, position: "MF", name: "백상훈" },
    { number: 14, position: "MF", name: "이지원" },
    { number: 21, position: "MF", name: "이승준" },
    { number: 22, position: "MF", name: "이진석" },
    { number: 27, position: "MF", name: "김민우" },
    { number: 28, position: "MF", name: "홍진현" },
    { number: 34, position: "MF", name: "배원준" },
    { number: 38, position: "MF", name: "김민준" },
    { number: 41, position: "MF", name: "이준혁" },
    { number: 42, position: "MF", name: "김대원" },
    { number: 44, position: "MF", name: "이승재" },
    { number: 47, position: "MF", name: "홍재훈" },
    { number: 7, position: "FW", name: "변재영" },
    { number: 9, position: "FW", name: "김훈옥" },
    { number: 10, position: "FW", name: "윤동권" },
    { number: 11, position: "FW", name: "박지열" },
    { number: 19, position: "FW", name: "엄하은" },
    { number: 25, position: "FW", name: "안기훈" },
    { number: 30, position: "FW", name: "김해수" },
    { number: 37, position: "FW", name: "김도형" },
    { number: 39, position: "FW", name: "김기현" },
    { number: 45, position: "FW", name: "홍준혁" },
    // 아래 3명은 구단 공식 인스타그램 "WELCOME TO SEOSAN" 영입 발표(2026-07)에서 확인한 사진 - 나무위키
    // 명단에는 아직 반영 안 됨. 경현호(37번)는 기존 명단의 김도형과 번호가 겹치는데(원문 그대로 반영,
    // 여주FC 77번 중복 사례와 동일 처리), 정우주는 발표 게시물에 등번호가 없어 null로 둔다.
    { number: 49, position: "FW", name: "박준혁", photo: "/img/k3k4players/seosan/49_박준혁.jpg" },
    { number: 37, position: "DF", name: "경현호", photo: "/img/k3k4players/seosan/37_경현호.jpg" },
    { number: null, position: "DF", name: "정우주", photo: "/img/k3k4players/seosan/정우주.jpg" },
  ],
  7068: [ // 대전코레일FC
    { number: 1, position: "GK", name: "백경인" },
    { number: 18, position: "GK", name: "김철호" },
    { number: 21, position: "GK", name: "배서준" },
    { number: 2, position: "DF", name: "김영인" },
    { number: 3, position: "DF", name: "황준석" },
    { number: 4, position: "DF", name: "김윤진" },
    { number: 5, position: "DF", name: "전인규" },
    { number: 8, position: "DF", name: "강효온" },
    { number: 10, position: "DF", name: "이인규" },
    { number: 13, position: "DF", name: "손경환" },
    { number: 15, position: "DF", name: "남윤재" },
    { number: 33, position: "DF", name: "최선우" },
    { number: 44, position: "DF", name: "전우람" },
    { number: 66, position: "DF", name: "김현우" },
    { number: 6, position: "MF", name: "박승렬" },
    { number: 14, position: "MF", name: "김동욱" },
    { number: 20, position: "MF", name: "김동섭" },
    { number: 22, position: "MF", name: "김광희" },
    { number: 26, position: "MF", name: "이관표" },
    { number: 34, position: "MF", name: "진지강" },
    { number: 38, position: "MF", name: "조한진" },
    { number: 77, position: "MF", name: "유지민" },
    { number: 7, position: "FW", name: "김정주" },
    { number: 9, position: "FW", name: "홍진민" },
    { number: 11, position: "FW", name: "김희성" },
    { number: 16, position: "FW", name: "송민종" },
    { number: 17, position: "FW", name: "박찬빈" },
    { number: 88, position: "FW", name: "박예찬" },
    { number: 91, position: "FW", name: "양창훈" },
  ],
  7059: [ // 창원FC
    { number: 13, position: "GK", name: "임채훈" },
    { number: 21, position: "GK", name: "이세민" },
    { number: 23, position: "GK", name: "손재혁" },
    { number: 3, position: "DF", name: "이지형" },
    { number: 4, position: "DF", name: "한상규" },
    { number: 11, position: "DF", name: "김우홍" },
    { number: 12, position: "DF", name: "한원재" },
    { number: 16, position: "DF", name: "김원준" },
    { number: 18, position: "DF", name: "신승민" },
    { number: 19, position: "DF", name: "한재훈" },
    { number: 22, position: "DF", name: "구재승" },
    { number: 40, position: "DF", name: "김원균" },
    { number: 66, position: "DF", name: "이승현" },
    { number: 88, position: "DF", name: "정성우" },
    { number: 5, position: "MF", name: "박진홍" },
    { number: 7, position: "MF", name: "예병원" },
    { number: 8, position: "MF", name: "이종훈" },
    { number: 9, position: "MF", name: "고병범" },
    { number: 10, position: "MF", name: "태현찬" },
    { number: 39, position: "MF", name: "김정현" },
    { number: 47, position: "MF", name: "이재민" },
    { number: 77, position: "MF", name: "이현성" },
    { number: 14, position: "FW", name: "홍정훈" },
    { number: 15, position: "FW", name: "장영기" },
    { number: 17, position: "FW", name: "홍지민" },
    { number: 20, position: "FW", name: "박세민" },
    { number: 29, position: "FW", name: "김해승" },
    { number: 70, position: "FW", name: "이종열" },
    { number: 99, position: "FW", name: "이동현" },
  ],
  7112: [ // 여주FC (나무위키 원문에 77번이 최상헌/이현왕 2명으로 중복 표기됨 - 그대로 반영)
    { number: 1, position: "GK", name: "김형수" },
    { number: 12, position: "GK", name: "서원" },
    { number: 31, position: "GK", name: "김상재" },
    { number: 2, position: "DF", name: "정기현" },
    { number: 4, position: "DF", name: "김형수" },
    { number: 5, position: "DF", name: "이해담" },
    { number: 6, position: "DF", name: "이동건" },
    { number: 15, position: "DF", name: "장재원" },
    { number: 17, position: "DF", name: "김준서" },
    { number: 19, position: "DF", name: "최정훈" },
    { number: 20, position: "DF", name: "김진성" },
    { number: 24, position: "DF", name: "박준택" },
    { number: 25, position: "DF", name: "이지원" },
    { number: 26, position: "DF", name: "김진혁" },
    { number: 29, position: "DF", name: "안성준" },
    { number: 32, position: "DF", name: "박준엽" },
    { number: 3, position: "MF", name: "오상준" },
    { number: 7, position: "MF", name: "이승민" },
    { number: 8, position: "MF", name: "최형우" },
    { number: 10, position: "MF", name: "이시이" },
    { number: 18, position: "MF", name: "임규현" },
    { number: 21, position: "MF", name: "전문수" },
    { number: 22, position: "MF", name: "조성우" },
    { number: 23, position: "MF", name: "장혁재" },
    { number: 27, position: "MF", name: "황지상" },
    { number: 47, position: "MF", name: "김윤겸" },
    { number: 66, position: "MF", name: "강태욱" },
    { number: 77, position: "MF", name: "최상헌" },
    { number: 77, position: "MF", name: "이현왕" },
    { number: 9, position: "FW", name: "문경민" },
    { number: 11, position: "FW", name: "정종근" },
    { number: 14, position: "FW", name: "서선웅" },
    { number: 16, position: "FW", name: "강민성" },
    { number: 28, position: "FW", name: "송지완" },
    { number: 30, position: "FW", name: "강민재" },
    { number: 37, position: "FW", name: "정은우" },
    { number: 70, position: "FW", name: "정인증" },
    { number: 71, position: "FW", name: "장유민" },
    { number: 72, position: "FW", name: "류지민" },
  ],
  7108: [ // 울산시민축구단
    { number: 1, position: "GK", name: "노우석" },
    { number: 18, position: "GK", name: "이선일" },
    { number: 31, position: "GK", name: "유영서" },
    { number: 3, position: "DF", name: "김재현" },
    { number: 4, position: "DF", name: "김기수" },
    { number: 5, position: "DF", name: "김민기" },
    { number: 8, position: "DF", name: "박동혁" },
    { number: 13, position: "DF", name: "김기영" },
    { number: 14, position: "DF", name: "김동윤" },
    { number: 16, position: "DF", name: "김유성" },
    { number: 21, position: "DF", name: "김성진" },
    { number: 24, position: "DF", name: "신성학" },
    { number: 29, position: "DF", name: "김태환" },
    { number: 33, position: "DF", name: "유원종" },
    { number: 6, position: "MF", name: "부성혁" },
    { number: 10, position: "MF", name: "윤대원" },
    { number: 22, position: "MF", name: "이한새" },
    { number: 25, position: "MF", name: "이준영" },
    { number: 26, position: "MF", name: "강민재" },
    { number: 47, position: "MF", name: "권혁찬" },
    { number: 77, position: "MF", name: "한빈" },
    { number: 7, position: "FW", name: "손민영" },
    { number: 9, position: "FW", name: "이기운" },
    { number: 11, position: "FW", name: "이기준" },
    { number: 12, position: "FW", name: "김용민" },
    { number: 17, position: "FW", name: "김세응" },
    { number: 19, position: "FW", name: "박상현" },
    { number: 96, position: "FW", name: "김재철" },
  ],
  7075: [ // FC강릉
    { number: 1, position: "GK", name: "황한준" },
    { number: 13, position: "GK", name: "김연수" },
    { number: 30, position: "GK", name: "한지율" },
    { number: 3, position: "DF", name: "김믿음" },
    { number: 19, position: "DF", name: "심정용" },
    { number: 20, position: "DF", name: "이주영" },
    { number: 21, position: "DF", name: "김길훈" },
    { number: 24, position: "DF", name: "이성윤" },
    { number: 34, position: "DF", name: "김재봉" },
    { number: 37, position: "DF", name: "황정욱" },
    { number: 40, position: "DF", name: "권순호" },
    { number: 91, position: "DF", name: "김훈민" },
    { number: 6, position: "MF", name: "송영민" },
    { number: 8, position: "MF", name: "장동혁" },
    { number: 10, position: "MF", name: "박하빈" },
    { number: 14, position: "MF", name: "구승훈" },
    { number: 17, position: "MF", name: "손정민" },
    { number: 22, position: "MF", name: "이형욱" },
    { number: 31, position: "MF", name: "김성순" },
    { number: 77, position: "MF", name: "송태성" },
    { number: 7, position: "FW", name: "우병철" },
    { number: 9, position: "FW", name: "조건규" },
    { number: 11, position: "FW", name: "김원준" },
    { number: 16, position: "FW", name: "김장우" },
    { number: 18, position: "FW", name: "송준민" },
    { number: 23, position: "FW", name: "이현규" },
    { number: 27, position: "FW", name: "권태영" },
    { number: 36, position: "FW", name: "손민범" },
    { number: 39, position: "FW", name: "최성민" },
    { number: 47, position: "FW", name: "이희재" },
    { number: 99, position: "FW", name: "김성현" },
  ],
  7064: [ // 춘천시민축구단
    { number: 1, position: "GK", name: "박민선" },
    { number: 19, position: "GK", name: "김도현" },
    { number: 21, position: "GK", name: "김성민" },
    { number: 2, position: "DF", name: "신기환" },
    { number: 3, position: "DF", name: "이재용" },
    { number: 4, position: "DF", name: "한용수" },
    { number: 5, position: "DF", name: "박현우" },
    { number: 6, position: "DF", name: "김승찬" },
    { number: 7, position: "DF", name: "박선용" },
    { number: 20, position: "DF", name: "권진영" },
    { number: 23, position: "DF", name: "마지강" },
    { number: 28, position: "DF", name: "김호경" },
    { number: 8, position: "MF", name: "윤성한" },
    { number: 14, position: "MF", name: "오형택" },
    { number: 16, position: "MF", name: "석린" },
    { number: 17, position: "MF", name: "김민수" },
    { number: 25, position: "MF", name: "김태현" },
    { number: 32, position: "MF", name: "이준원" },
    { number: 39, position: "MF", name: "코바야시 칸" },
    { number: 61, position: "MF", name: "허동호" },
    { number: 77, position: "MF", name: "정승현" },
    { number: 97, position: "MF", name: "이명동" },
    { number: 9, position: "FW", name: "김민우" },
    { number: 10, position: "FW", name: "신상휘" },
    { number: 11, position: "FW", name: "이광재" },
    { number: 18, position: "FW", name: "마테우스 데벨라르" },
    { number: 33, position: "FW", name: "루카스 올리베이라" },
    { number: 90, position: "FW", name: "김형준" },
    { number: 88, position: null, name: "이성민" },
  ],
  7096: [ // FC목포
    { number: 1, position: "GK", name: "최성겸" },
    { number: 21, position: "GK", name: "한승협" },
    { number: 31, position: "GK", name: "박종건" },
    { number: 2, position: "DF", name: "이제승" },
    { number: 3, position: "DF", name: "이태윤" },
    { number: 4, position: "DF", name: "이규석" },
    { number: 5, position: "DF", name: "이건웅" },
    { number: 6, position: "DF", name: "심원성" },
    { number: 7, position: "DF", name: "김규민" },
    { number: 13, position: "DF", name: "오승진" },
    { number: 16, position: "DF", name: "김민재" },
    { number: 17, position: "DF", name: "전보민" },
    { number: 22, position: "DF", name: "이중호" },
    { number: 26, position: "DF", name: "강영종" },
    { number: 32, position: "DF", name: "김정우" },
    { number: 8, position: "MF", name: "양준모" },
    { number: 14, position: "MF", name: "안성주" },
    { number: 23, position: "MF", name: "공용훈" },
    { number: 27, position: "MF", name: "이현탁" },
    { number: 9, position: "FW", name: "장한영" },
    { number: 10, position: "FW", name: "이정" },
    { number: 11, position: "FW", name: "안경찬" },
    { number: 18, position: "FW", name: "이태응" },
    { number: 19, position: "FW", name: "정기운" },
    { number: 20, position: "FW", name: "이찬울" },
    { number: 33, position: "FW", name: "박정우" },
    { number: 70, position: "FW", name: "성힘찬" },
    { number: 72, position: "FW", name: "서명식" },
    { number: 88, position: "FW", name: "차승규" },
  ],
  25717: [ // 전북현대모터스 B팀(나무위키 "전북 현대 모터스 N")
    { number: 29, position: "GK", name: "공시현" },
    { number: 51, position: "GK", name: "이한결" },
    { number: 91, position: "GK", name: "정대영" },
    { number: 15, position: "DF", name: "김하준" },
    { number: 22, position: "DF", name: "김준영" },
    { number: 27, position: "DF", name: "황승준" },
    { number: 39, position: "DF", name: "서정혁" },
    { number: 42, position: "DF", name: "우현수" },
    { number: 44, position: "DF", name: "김주형" },
    { number: 55, position: "DF", name: "최진웅" },
    { number: 74, position: "DF", name: "김수형" },
    { number: 80, position: "DF", name: "곽희벽" },
    { number: 26, position: "MF", name: "문준혁" },
    { number: 30, position: "MF", name: "김영환" },
    { number: 33, position: "MF", name: "한석진" },
    { number: 36, position: "MF", name: "장남웅" },
    { number: 40, position: "MF", name: "안태훈" },
    { number: 47, position: "MF", name: "이건희" },
    { number: 70, position: "MF", name: "박현민" },
    { number: 88, position: "MF", name: "윤현석" },
    { number: 34, position: "FW", name: "엄승민" },
    { number: 79, position: "FW", name: "김창훈" },
    { number: 90, position: "FW", name: "정상운" },
    { number: 92, position: "FW", name: "김두현" },
    { number: 98, position: "FW", name: "임준휘" },
  ],
  27858: [ // 금산인삼FC (사용자 제공 구단 공식 선수단 화면 캡처 기준 - 포지션 확인됨, 2026-08-08)
    { number: 1, position: "GK", name: "김현우" },
    { number: 2, position: "DF", name: "김민재" },
    { number: 5, position: "DF", name: "이충" },
    { number: 6, position: "FW", name: "장시헌" },
    { number: 7, position: "FW", name: "민성연" },
    { number: 8, position: "MF", name: "박준하" },
    { number: 10, position: "MF", name: "양세영" },
    { number: 11, position: "FW", name: "이인학" },
    { number: 13, position: "DF", name: "조수빈" },
    { number: 14, position: "MF", name: "이민재" },
    { number: 15, position: "DF", name: "이우진" },
    { number: 16, position: "MF", name: "박이건" },
    { number: 17, position: "FW", name: "이지홍" },
    { number: 18, position: "FW", name: "이선우" },
    { number: 19, position: "MF", name: "서경주" },
    { number: 20, position: "DF", name: "이건우" },
    { number: 21, position: "GK", name: "박희근" },
    { number: 22, position: "FW", name: "문슬범" },
    { number: 24, position: "DF", name: "권민우" },
    { number: 27, position: "MF", name: "백승우" },
    { number: 28, position: "MF", name: "심현욱" },
    { number: 30, position: "MF", name: "이상민" },
    { number: 31, position: "DF", name: "나지후" },
    { number: 32, position: "FW", name: "류수혁" },
    { number: 33, position: "GK", name: "성윤수" },
    { number: 34, position: "MF", name: "고경록" },
    { number: 35, position: "FW", name: "전정호" },
    { number: 37, position: "FW", name: "이재의" },
    { number: 38, position: "MF", name: "박태인" },
    { number: 44, position: "FW", name: "안현수" },
    { number: 47, position: "MF", name: "김선욱" },
    { number: 49, position: "DF", name: "김도영" },
    { number: 50, position: "DF", name: "정한철" },
  ],
  27860: [ // 제천시민축구단 (공식 사이트 jecheoncityfc.com 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "홍진웅", photo: "/img/k3k4players/jecheon/jecheon_홍진웅.jpg" },
    { number: 21, position: "GK", name: "주호연", photo: "/img/k3k4players/jecheon/jecheon_주호연.jpg" },
    { number: 31, position: "GK", name: "남윤성", photo: "/img/k3k4players/jecheon/jecheon_남윤성.jpg" },
    { number: 3, position: "DF", name: "노윤상", photo: "/img/k3k4players/jecheon/jecheon_노윤상.jpg" },
    { number: 4, position: "DF", name: "우태민", photo: "/img/k3k4players/jecheon/jecheon_우태민.jpg" },
    { number: 5, position: "DF", name: "이태인", photo: "/img/k3k4players/jecheon/jecheon_이태인.jpg" },
    { number: 12, position: "DF", name: "김태훈", photo: "/img/k3k4players/jecheon/jecheon_김태훈.jpg" },
    { number: 15, position: "DF", name: "이진웅", photo: "/img/k3k4players/jecheon/jecheon_이진웅.jpg" },
    { number: 17, position: "DF", name: "박상우", photo: "/img/k3k4players/jecheon/jecheon_박상우.jpg" },
    { number: 22, position: "DF", name: "양현진", photo: "/img/k3k4players/jecheon/jecheon_양현진.jpg" },
    { number: 23, position: "DF", name: "박병주", photo: "/img/k3k4players/jecheon/jecheon_박병주.jpg" },
    { number: 25, position: "DF", name: "김현성", photo: "/img/k3k4players/jecheon/jecheon_김현성.jpg" },
    { number: 27, position: "DF", name: "천인수", photo: "/img/k3k4players/jecheon/jecheon_천인수.jpg" },
    { number: 36, position: "DF", name: "이승빈", photo: "/img/k3k4players/jecheon/jecheon_이승빈.jpg" },
    { number: 43, position: "DF", name: "김윤환", photo: "/img/k3k4players/jecheon/jecheon_김윤환.jpg" },
    { number: 6, position: "MF", name: "장현수", photo: "/img/k3k4players/jecheon/jecheon_장현수.jpg" },
    { number: 8, position: "MF", name: "정혁", photo: "/img/k3k4players/jecheon/jecheon_정혁.jpg" },
    { number: 10, position: "MF", name: "조완", photo: "/img/k3k4players/jecheon/jecheon_조완.jpg" },
    { number: 11, position: "MF", name: "김건남", photo: "/img/k3k4players/jecheon/jecheon_김건남.jpg" },
    { number: 13, position: "MF", name: "안태욱", photo: "/img/k3k4players/jecheon/jecheon_안태욱.jpg" },
    { number: 14, position: "MF", name: "이승우", photo: "/img/k3k4players/jecheon/jecheon_이승우.jpg" },
    { number: 16, position: "MF", name: "천은원", photo: "/img/k3k4players/jecheon/jecheon_천은원.jpg" },
    { number: 18, position: "MF", name: "박태원", photo: "/img/k3k4players/jecheon/jecheon_박태원.jpg" },
    { number: 19, position: "MF", name: "유동현", photo: "/img/k3k4players/jecheon/jecheon_유동현.jpg" },
    { number: 26, position: "MF", name: "오솔본", photo: "/img/k3k4players/jecheon/jecheon_오솔본.jpg" },
    { number: 30, position: "MF", name: "안영", photo: "/img/k3k4players/jecheon/jecheon_안영.jpg" },
    { number: 32, position: "MF", name: "이차민", photo: "/img/k3k4players/jecheon/jecheon_이차민.jpg" },
    { number: 33, position: "MF", name: "강보승", photo: "/img/k3k4players/jecheon/jecheon_강보승.jpg" },
    { number: 34, position: "MF", name: "노승기", photo: "/img/k3k4players/jecheon/jecheon_노승기.jpg" },
    { number: 40, position: "MF", name: "조동인", photo: "/img/k3k4players/jecheon/jecheon_조동인.jpg" },
    { number: 42, position: "MF", name: "정재민", photo: "/img/k3k4players/jecheon/jecheon_정재민.jpg" },
    { number: 7, position: "FW", name: "한석희", photo: "/img/k3k4players/jecheon/jecheon_한석희.jpg" },
    { number: 9, position: "FW", name: "박시언", photo: "/img/k3k4players/jecheon/jecheon_박시언.jpg" },
    { number: 29, position: "FW", name: "손주원", photo: "/img/k3k4players/jecheon/jecheon_손주원.jpg" },
    { number: 41, position: "FW", name: "정택현", photo: "/img/k3k4players/jecheon/jecheon_정택현.jpg" },
  ],
  23089: [ // 남양주시민축구단 (공식 사이트 nyjfc.com 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "박한근", photo: "/img/k3k4players/namyangju/namyangju_박한근.jpg" },
    { number: 29, position: "GK", name: "김민재", photo: "/img/k3k4players/namyangju/namyangju_김민재.jpg" },
    { number: 31, position: "GK", name: "김민서", photo: "/img/k3k4players/namyangju/namyangju_김민서.jpg" },
    { number: 3, position: "DF", name: "조경찬", photo: "/img/k3k4players/namyangju/namyangju_조경찬.jpg" },
    { number: 4, position: "DF", name: "이태극", photo: "/img/k3k4players/namyangju/namyangju_이태극.jpg" },
    { number: 7, position: "DF", name: "안재준", photo: "/img/k3k4players/namyangju/namyangju_안재준.jpg" },
    { number: 11, position: "DF", name: "이새한", photo: "/img/k3k4players/namyangju/namyangju_이새한.jpg" },
    { number: 17, position: "DF", name: "유수환", photo: "/img/k3k4players/namyangju/namyangju_유수환.jpg" },
    { number: 19, position: "DF", name: "김승진", photo: "/img/k3k4players/namyangju/namyangju_김승진.jpg" },
    { number: 20, position: "DF", name: "고태규", photo: "/img/k3k4players/namyangju/namyangju_고태규.jpg" },
    { number: 26, position: "DF", name: "유영재", photo: "/img/k3k4players/namyangju/namyangju_유영재.jpg" },
    { number: 55, position: "DF", name: "김규환", photo: "/img/k3k4players/namyangju/namyangju_김규환.jpg" },
    { number: 77, position: "DF", name: "신성재", photo: "/img/k3k4players/namyangju/namyangju_신성재.jpg" },
    { number: 5, position: "MF", name: "황기욱", photo: "/img/k3k4players/namyangju/namyangju_황기욱.jpg" },
    { number: 6, position: "MF", name: "김태영", photo: "/img/k3k4players/namyangju/namyangju_김태영.jpg" },
    { number: 8, position: "MF", name: "서여준", photo: "/img/k3k4players/namyangju/namyangju_서여준.jpg" },
    { number: 16, position: "MF", name: "김경환", photo: "/img/k3k4players/namyangju/namyangju_김경환.jpg" },
    { number: 23, position: "MF", name: "박제영", photo: "/img/k3k4players/namyangju/namyangju_박제영.jpg" },
    { number: 28, position: "MF", name: "김유빈", photo: "/img/k3k4players/namyangju/namyangju_김유빈.jpg" },
    { number: 30, position: "MF", name: "김효기", photo: "/img/k3k4players/namyangju/namyangju_김효기.jpg" },
    { number: 38, position: "MF", name: "문성욱", photo: "/img/k3k4players/namyangju/namyangju_문성욱.jpg" },
    { number: 10, position: "FW", name: "구현우", photo: "/img/k3k4players/namyangju/namyangju_구현우.jpg" },
    { number: 13, position: "FW", name: "강민승", photo: "/img/k3k4players/namyangju/namyangju_강민승.jpg" },
    { number: 18, position: "FW", name: "김진환", photo: "/img/k3k4players/namyangju/namyangju_김진환.jpg" },
    { number: 21, position: "FW", name: "최준영", photo: "/img/k3k4players/namyangju/namyangju_최준영.jpg" },
    { number: 41, position: "FW", name: "박효민", photo: "/img/k3k4players/namyangju/namyangju_박효민.jpg" },
    { number: 71, position: "FW", name: "권기현", photo: "/img/k3k4players/namyangju/namyangju_권기현.jpg" },
    { number: 90, position: "FW", name: "권구민", photo: "/img/k3k4players/namyangju/namyangju_권구민.jpg" },
    { number: 99, position: "FW", name: "손석용", photo: "/img/k3k4players/namyangju/namyangju_손석용.jpg" },
  ],
  25720: [ // 세종SA축구단 (공식 사이트 sejongsa.co.kr 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "이재훈", photo: "/img/k3k4players/sejong/sejong_이재훈.jpg" },
    { number: 18, position: "GK", name: "심지섭", photo: "/img/k3k4players/sejong/sejong_심지섭.jpg" },
    { number: 31, position: "GK", name: "김윤재", photo: "/img/k3k4players/sejong/sejong_김윤재.jpg" },
    { number: 81, position: "GK", name: "강대규", photo: "/img/k3k4players/sejong/sejong_강대규.jpg" },
    { number: 2, position: "DF", name: "우민걸", photo: "/img/k3k4players/sejong/sejong_우민걸.jpg" },
    { number: 3, position: "DF", name: "장경호", photo: "/img/k3k4players/sejong/sejong_장경호.jpg" },
    { number: 4, position: "DF", name: "정용수", photo: "/img/k3k4players/sejong/sejong_정용수.jpg" },
    { number: 5, position: "DF", name: "이민형", photo: "/img/k3k4players/sejong/sejong_이민형.jpg" },
    { number: 15, position: "DF", name: "김광룡", photo: "/img/k3k4players/sejong/sejong_김광룡.jpg" },
    { number: 21, position: "DF", name: "김영환", photo: "/img/k3k4players/sejong/sejong_김영환.jpg" },
    { number: 23, position: "DF", name: "유창현", photo: "/img/k3k4players/sejong/sejong_유창현.jpg" },
    { number: 24, position: "DF", name: "금유섭", photo: "/img/k3k4players/sejong/sejong_금유섭.jpg" },
    { number: 26, position: "DF", name: "김두람", photo: "/img/k3k4players/sejong/sejong_김두람.jpg" },
    { number: 27, position: "DF", name: "조민재", photo: "/img/k3k4players/sejong/sejong_조민재.jpg" },
    { number: 30, position: "DF", name: "곽승민", photo: "/img/k3k4players/sejong/sejong_곽승민.jpg" },
    { number: 32, position: "DF", name: "장호성", photo: "/img/k3k4players/sejong/sejong_장호성.jpg" },
    { number: 33, position: "DF", name: "하지성", photo: "/img/k3k4players/sejong/sejong_하지성.jpg" },
    { number: 34, position: "DF", name: "나영현", photo: "/img/k3k4players/sejong/sejong_나영현.jpg" },
    { number: 40, position: "DF", name: "신동욱", photo: "/img/k3k4players/sejong/sejong_신동욱.jpg" },
    { number: 62, position: "DF", name: "양영준", photo: "/img/k3k4players/sejong/sejong_양영준.jpg" },
    { number: 66, position: "DF", name: "정선홍", photo: "/img/k3k4players/sejong/sejong_정선홍.jpg" },
    { number: 76, position: "DF", name: "이병훈", photo: "/img/k3k4players/sejong/sejong_이병훈.jpg" },
    { number: 99, position: "DF", name: "홍해성", photo: "/img/k3k4players/sejong/sejong_홍해성.jpg" },
    { number: 6, position: "MF", name: "장성재", photo: "/img/k3k4players/sejong/sejong_장성재.jpg" },
    { number: 7, position: "MF", name: "김태윤", photo: "/img/k3k4players/sejong/sejong_김태윤.jpg" },
    { number: 8, position: "MF", name: "윤용호", photo: "/img/k3k4players/sejong/sejong_윤용호.jpg" },
    { number: 9, position: "MF", name: "김지한", photo: "/img/k3k4players/sejong/sejong_김지한.jpg" },
    { number: 10, position: "MF", name: "김재석", photo: "/img/k3k4players/sejong/sejong_김재석.jpg" },
    { number: 11, position: "MF", name: "이재석", photo: "/img/k3k4players/sejong/sejong_이재석.jpg" },
    { number: 13, position: "MF", name: "조재민", photo: "/img/k3k4players/sejong/sejong_조재민.jpg" },
    { number: 14, position: "MF", name: "하용민", photo: "/img/k3k4players/sejong/sejong_하용민.jpg" },
    { number: 16, position: "MF", name: "김도헌", photo: "/img/k3k4players/sejong/sejong_김도헌.jpg" },
    { number: 25, position: "MF", name: "강재우", photo: "/img/k3k4players/sejong/sejong_강재우.jpg" },
    { number: 29, position: "MF", name: "구민준", photo: "/img/k3k4players/sejong/sejong_구민준.jpg" },
    { number: 44, position: "MF", name: "남진희", photo: "/img/k3k4players/sejong/sejong_남진희.jpg" },
    { number: 47, position: "MF", name: "성기완", photo: "/img/k3k4players/sejong/sejong_성기완.jpg" },
    { number: 77, position: "MF", name: "최재훈", photo: "/img/k3k4players/sejong/sejong_최재훈.jpg" },
    { number: 88, position: "MF", name: "김원형", photo: "/img/k3k4players/sejong/sejong_김원형.jpg" },
    { number: 98, position: "MF", name: "성문경", photo: "/img/k3k4players/sejong/sejong_성문경.jpg" },
    { number: 12, position: "FW", name: "김우진", photo: "/img/k3k4players/sejong/sejong_김우진.jpg" },
    { number: 17, position: "FW", name: "민동후", photo: "/img/k3k4players/sejong/sejong_민동후.jpg" },
    { number: 19, position: "FW", name: "유정완", photo: "/img/k3k4players/sejong/sejong_유정완.jpg" },
    { number: 22, position: "FW", name: "박준이", photo: "/img/k3k4players/sejong/sejong_박준이.jpg" },
    { number: 28, position: "FW", name: "양항", photo: "/img/k3k4players/sejong/sejong_양항.jpg" },
    { number: 37, position: "FW", name: "김성빈", photo: "/img/k3k4players/sejong/sejong_김성빈.jpg" },
    { number: 42, position: "FW", name: "육재경", photo: "/img/k3k4players/sejong/sejong_육재경.jpg" },
    { number: 70, position: "FW", name: "이서준", photo: "/img/k3k4players/sejong/sejong_이서준.jpg" },
    { number: 71, position: "FW", name: "승준서", photo: "/img/k3k4players/sejong/sejong_승준서.jpg" },
    { number: 80, position: "FW", name: "김정우", photo: "/img/k3k4players/sejong/sejong_김정우.jpg" },
    { number: 91, position: "FW", name: "허원준", photo: "/img/k3k4players/sejong/sejong_허원준.jpg" },
  ],
  18656: [ // 평창유나이티드축구클럽
    { number: 1, position: "GK", name: "유승완" },
    { number: 21, position: "GK", name: "유종민" },
    { number: 31, position: "GK", name: "홍정훈" },
    { number: 2, position: "DF", name: "최창원" },
    { number: 6, position: "DF", name: "지병우" },
    { number: 10, position: "DF", name: "김용태" },
    { number: 11, position: "DF", name: "정민우" },
    { number: 17, position: "DF", name: "김시온" },
    { number: 25, position: "DF", name: "정재훈" },
    { number: 27, position: "DF", name: "김재현" },
    { number: 32, position: "DF", name: "이병욱" },
    { number: 66, position: "DF", name: "이동은" },
    { number: 77, position: "DF", name: "양희도" },
    { number: 88, position: "DF", name: "황문기" },
    { number: 5, position: "MF", name: "김세호" },
    { number: 8, position: "MF", name: "신지훈" },
    { number: 14, position: "MF", name: "양군호" },
    { number: 22, position: "MF", name: "김도윤" },
    { number: 23, position: "MF", name: "김희재" },
    { number: 24, position: "MF", name: "배현세" },
    { number: 30, position: "MF", name: "조승환" },
    { number: 94, position: "MF", name: "박요한" },
    { number: 7, position: "FW", name: "마틴 사위" },
    { number: 9, position: "FW", name: "정성준" },
    { number: 13, position: "FW", name: "조정빈" },
    { number: 18, position: "FW", name: "성정윤" },
    { number: 19, position: "FW", name: "김건우" },
    { number: 26, position: "FW", name: "조민성" },
    { number: 28, position: "FW", name: "오재혁" },
    { number: 33, position: "FW", name: "우도 프린스" },
    { number: 47, position: "FW", name: "유재마" },
  ],
  25719: [ // 기장군민축구단 (공식 사이트 gijangunited.com 기준, 사진 포함 - 2026-08-08)
    { number: 13, position: "GK", name: "김민근", photo: "/img/k3k4players/gijang/gijang_김민근.jpg" },
    { number: 18, position: "GK", name: "이민혁", photo: "/img/k3k4players/gijang/gijang_이민혁.jpg" },
    { number: 2, position: "DF", name: "박진배", photo: "/img/k3k4players/gijang/gijang_박진배.jpg" },
    { number: 4, position: "DF", name: "이주성", photo: "/img/k3k4players/gijang/gijang_이주성.jpg" },
    { number: 5, position: "DF", name: "박현응", photo: "/img/k3k4players/gijang/gijang_박현응.jpg" },
    { number: 6, position: "DF", name: "김대원", photo: "/img/k3k4players/gijang/gijang_김대원.jpg" },
    { number: 19, position: "DF", name: "최현빈", photo: "/img/k3k4players/gijang/gijang_최현빈.jpg" },
    { number: 40, position: "DF", name: "최규민", photo: "/img/k3k4players/gijang/gijang_최규민.jpg" },
    { number: 41, position: "DF", name: "이호준", photo: "/img/k3k4players/gijang/gijang_이호준.jpg" },
    { number: 55, position: "DF", name: "권경륜", photo: "/img/k3k4players/gijang/gijang_권경륜.jpg" },
    { number: 8, position: "MF", name: "신윤호", photo: "/img/k3k4players/gijang/gijang_신윤호.jpg" },
    { number: 10, position: "MF", name: "김기찬", photo: "/img/k3k4players/gijang/gijang_김기찬.jpg" },
    { number: 14, position: "MF", name: "전효석", photo: "/img/k3k4players/gijang/gijang_전효석.jpg" },
    { number: 16, position: "MF", name: "김현범", photo: "/img/k3k4players/gijang/gijang_김현범.jpg" },
    { number: 20, position: "MF", name: "조재혁", photo: "/img/k3k4players/gijang/gijang_조재혁.jpg" },
    { number: 21, position: "MF", name: "오승현", photo: "/img/k3k4players/gijang/gijang_오승현.jpg" },
    { number: 23, position: "MF", name: "장원별", photo: "/img/k3k4players/gijang/gijang_장원별.jpg" },
    { number: 25, position: "MF", name: "이종안", photo: "/img/k3k4players/gijang/gijang_이종안.jpg" },
    { number: 71, position: "MF", name: "김민결", photo: "/img/k3k4players/gijang/gijang_김민결.jpg" },
    { number: 77, position: "MF", name: "고동현", photo: "/img/k3k4players/gijang/gijang_고동현.jpg" },
    { number: 88, position: "MF", name: "김종현", photo: "/img/k3k4players/gijang/gijang_김종현.jpg" },
    { number: 7, position: "FW", name: "임예닮", photo: "/img/k3k4players/gijang/gijang_임예닮.jpg" },
    { number: 9, position: "FW", name: "김하준", photo: "/img/k3k4players/gijang/gijang_김하준.jpg" },
    { number: 11, position: "FW", name: "김동현", photo: "/img/k3k4players/gijang/gijang_김동현.jpg" },
    { number: 15, position: "FW", name: "김지홍", photo: "/img/k3k4players/gijang/gijang_김지홍.jpg" },
    { number: 17, position: "FW", name: "이정훈", photo: "/img/k3k4players/gijang/gijang_이정훈.jpg" },
    { number: 22, position: "FW", name: "노수인", photo: "/img/k3k4players/gijang/gijang_노수인.jpg" },
    { number: 27, position: "FW", name: "김준수", photo: "/img/k3k4players/gijang/gijang_김준수.jpg" },
    { number: 29, position: "FW", name: "윤상연", photo: "/img/k3k4players/gijang/gijang_윤상연.jpg" },
    { number: 66, position: "FW", name: "차동근", photo: "/img/k3k4players/gijang/gijang_차동근.jpg" },
    { number: 79, position: "FW", name: "김지호", photo: "/img/k3k4players/gijang/gijang_김지호.jpg" },
    { number: 91, position: "FW", name: "김연중", photo: "/img/k3k4players/gijang/gijang_김연중.jpg" },
  ],
  27859: [ // 함안군민축구단 (공식 사이트 hamanfc.co.kr 기준, 사진 포함 - 2026-08-08)
    { number: 1, position: "GK", name: "권재현", photo: "/img/k3k4players/haman/haman_권재현.jpg" },
    { number: 21, position: "GK", name: "오찬식", photo: "/img/k3k4players/haman/haman_오찬식.jpg" },
    { number: 23, position: "GK", name: "이제민", photo: "/img/k3k4players/haman/haman_이제민.jpg" },
    { number: 42, position: "GK", name: "황치윤", photo: "/img/k3k4players/haman/haman_황치윤.jpg" },
    { number: 3, position: "DF", name: "전지훈", photo: "/img/k3k4players/haman/haman_전지훈.jpg" },
    { number: 4, position: "DF", name: "윤정민", photo: "/img/k3k4players/haman/haman_윤정민.jpg" },
    { number: 5, position: "DF", name: "서준우", photo: "/img/k3k4players/haman/haman_서준우.jpg" },
    { number: 7, position: "DF", name: "최용준", photo: "/img/k3k4players/haman/haman_최용준.jpg" },
    { number: 16, position: "DF", name: "채희서", photo: "/img/k3k4players/haman/haman_채희서.jpg" },
    { number: 24, position: "DF", name: "이한주", photo: "/img/k3k4players/haman/haman_이한주.jpg" },
    { number: 30, position: "DF", name: "천정욱", photo: "/img/k3k4players/haman/haman_천정욱.jpg" },
    { number: 32, position: "DF", name: "전우진", photo: "/img/k3k4players/haman/haman_전우진.jpg" },
    { number: 33, position: "DF", name: "김민웅", photo: "/img/k3k4players/haman/haman_김민웅.jpg" },
    { number: 37, position: "DF", name: "김카빈", photo: "/img/k3k4players/haman/haman_김카빈.jpg" },
    { number: 66, position: "DF", name: "송준민", photo: "/img/k3k4players/haman/haman_송준민.jpg" },
    { number: 2, position: "MF", name: "김도경", photo: "/img/k3k4players/haman/haman_김도경.jpg" },
    { number: 6, position: "MF", name: "양유민", photo: "/img/k3k4players/haman/haman_양유민.jpg" },
    { number: 8, position: "MF", name: "신지훈", photo: "/img/k3k4players/haman/haman_신지훈.jpg" },
    { number: 11, position: "MF", name: "신승일", photo: "/img/k3k4players/haman/haman_신승일.jpg" },
    { number: 13, position: "MF", name: "김진현", photo: "/img/k3k4players/haman/haman_김진현.jpg" },
    { number: 14, position: "MF", name: "서재혁", photo: "/img/k3k4players/haman/haman_서재혁.jpg" },
    { number: 15, position: "MF", name: "태현진", photo: "/img/k3k4players/haman/haman_태현진.jpg" },
    { number: 17, position: "MF", name: "김건우", photo: "/img/k3k4players/haman/haman_김건우.jpg" },
    { number: 19, position: "MF", name: "이주항", photo: "/img/k3k4players/haman/haman_이주항.jpg" },
    { number: 20, position: "MF", name: "김희건", photo: "/img/k3k4players/haman/haman_김희건.jpg" },
    { number: 25, position: "MF", name: "박세호", photo: "/img/k3k4players/haman/haman_박세호.jpg" },
    { number: 27, position: "MF", name: "이승준", photo: "/img/k3k4players/haman/haman_이승준.jpg" },
    { number: 31, position: "MF", name: "김성남", photo: "/img/k3k4players/haman/haman_김성남.jpg" },
    { number: 34, position: "MF", name: "곽민서", photo: "/img/k3k4players/haman/haman_곽민서.jpg" },
    { number: 47, position: "MF", name: "이상훈", photo: "/img/k3k4players/haman/haman_이상훈.jpg" },
    { number: 88, position: "MF", name: "김규표", photo: "/img/k3k4players/haman/haman_김규표.jpg" },
    { number: 9, position: "FW", name: "김성준", photo: "/img/k3k4players/haman/haman_김성준.jpg" },
    { number: 18, position: "FW", name: "김영광", photo: "/img/k3k4players/haman/haman_김영광.jpg" },
    { number: 28, position: "FW", name: "서예준", photo: "/img/k3k4players/haman/haman_서예준.jpg" },
    { number: 29, position: "FW", name: "정주성", photo: "/img/k3k4players/haman/haman_정주성.jpg" },
    { number: 99, position: "FW", name: "하재현", photo: "/img/k3k4players/haman/haman_하재현.jpg" },
  ],
  7101: [ // 평택시티즌FC
    { number: 21, position: "GK", name: "이정안" },
    { number: 99, position: "GK", name: "박지현" },
    { number: 2, position: "DF", name: "정희성" },
    { number: 3, position: "DF", name: "허태양" },
    { number: 4, position: "DF", name: "심영서" },
    { number: 5, position: "DF", name: "홍성민" },
    { number: 8, position: "DF", name: "이한빈" },
    { number: 15, position: "DF", name: "이훈" },
    { number: 20, position: "DF", name: "이준서" },
    { number: 22, position: "DF", name: "변우석" },
    { number: 23, position: "DF", name: "전정호" },
    { number: 27, position: "DF", name: "김민석" },
    { number: 39, position: "DF", name: "박동빈" },
    { number: 55, position: "DF", name: "배건우" },
    { number: 65, position: "DF", name: "이준기" },
    { number: 66, position: "DF", name: "권도윤" },
    { number: 71, position: "DF", name: "이인우" },
    { number: 6, position: "MF", name: "김백천" },
    { number: 13, position: "MF", name: "김윤성" },
    { number: 29, position: "MF", name: "김민수" },
    { number: 72, position: "MF", name: "정태율" },
    { number: 73, position: "MF", name: "박준수" },
    { number: 93, position: "MF", name: "정민의" },
    { number: 7, position: "FW", name: "박중현" },
    { number: 9, position: "FW", name: "정찬영" },
    { number: 10, position: "FW", name: "최성호" },
    { number: 11, position: "FW", name: "송호준" },
    { number: 12, position: "FW", name: "주민국" },
    { number: 14, position: "FW", name: "이도안" },
    { number: 16, position: "FW", name: "조영민" },
    { number: 17, position: "FW", name: "이건형" },
    { number: 18, position: "FW", name: "오승민" },
    { number: 19, position: "FW", name: "권유민" },
    { number: 24, position: "FW", name: "추영호" },
    { number: 26, position: "FW", name: "김민석" },
    { number: 33, position: "FW", name: "배현웅" },
    { number: 41, position: "FW", name: "정지호" },
    { number: 77, position: "FW", name: "김채웅" },
    { number: 79, position: "FW", name: "구하민" },
    { number: 88, position: "FW", name: "정현중" },
    { number: 89, position: "FW", name: "이승우" },
    { number: 97, position: "FW", name: "김주찬" },
  ],
};

// 프론트(teamDetail.js)의 포지션 그룹핑이 API-Football 원문 표기(Goalkeeper/Defender/Midfielder/
// Attacker)를 기준으로 하기 때문에, 나무위키에서 옮겨온 GK/DF/MF/FW 약어를 그에 맞춰 변환한다.
const POSITION_FULL_NAME = { GK: "Goalkeeper", DF: "Defender", MF: "Midfielder", FW: "Attacker" };

// API-Football이 K3/K4는 스쿼드를 아예 안 주거나(0명), 극히 일부만 등록해둔 경우(예: 3명)가 있어서
// "1명이라도 있으면 그대로 쓴다"로는 부족하다 - 실제 팀은 최소 20명 이상이라 이 미만이면 미완성으로
// 보고 나무위키 전체 명단으로 대체한다(진주시민축구단 등에서 확인, 2026-08-08).
const API_SQUAD_MIN_SIZE = 15;

export function lookupManualK3K4Squad(teamId, existingSquadLength) {
  if (existingSquadLength >= API_SQUAD_MIN_SIZE) return null; // API-Football이 충분한 스쿼드를 주면 그걸 우선한다
  const roster = MANUAL_K3K4_SQUADS[Number(teamId)];
  if (!roster) return null;
  const teamName = TEAM_NAME_FOR_PHOTO_LOOKUP[Number(teamId)];
  // 나무위키 원문에 등번호가 중복 표기된 경우가 있어서(예: 여주FC 77번 2명), 인덱스를 더해 id를 유일하게 만든다.
  return roster.map((p, i) => ({
    id: `manual-${teamId}-${p.number}-${i}`,
    name: p.name,
    position: POSITION_FULL_NAME[p.position] || null,
    nationality: null,
    number: p.number,
    age: null,
    // 로스터 항목 자체에 photo가 있으면(구단 공식 사이트에서 직접 확보한 사진) 그걸 우선 쓰고,
    // 없으면 예전 방식(k3k4PlayerPhotos.js의 팀명|이름 표)으로 폴백한다.
    photo: p.photo || (teamName ? lookupK3K4PlayerPhoto(teamName, p.name) : null),
  }));
}
